---
title: Goodbye Conway
author: James Riley
date: '2020-04-25'
slug: goodbye-conway
categories:
  - JavaScript
tags:
  - cellular automaton
  - Plotly
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
type: post
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	collapse = TRUE
)
set.seed(18369L)

```

The world has lost John Conway to covid-19. I recall my first interactions with Life - I had an offer to study undergrad maths at Cambridge. They recognised that folk from state schools were at a disadvantage to those from private schools for their own additional exam, so we got a crash course in the Easter holidays. Somehow Life came up in conversation with another student, and we ended up running the simulation with a deck of cards we had to hand, including moving a glider[^1] across the floor, one tick at a time. 

[Hackaday](https://hackaday.com/tag/john-horton-conway/) challenged us to program Life in memorial, so here goes.

There was some _ugly_ R code here that ran incredibly slowly. But then I've been reading [Eloquent JavaScript](https://eloquentjavascript.net/) and [Plotly]() was _designed_ for JavaScript, so it wasn't hard to go from plotting in R to plotting in JS. 

`r htmltools::HTML('<p class="codepen" data-height="600" data-theme-id="light" data-default-tab="js,result" data-user="jimr1603" data-slug-hash="rNOMEry" style="height: 600px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="Life">
  <span>See the Pen <a href="https://codepen.io/jimr1603/pen/rNOMEry">
  Life</a> by James Riley (<a href="https://codepen.io/jimr1603">@jimr1603</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>')`

A nice side-effect is that what you see above is uniquely running on your machine. 