---
title: Thanos did nothing wrong
author: James Riley
date: '2018-08-21'
slug: thanos-did-nothing-wrong
categories:
  - R
tags:
  - health economics
  - ethics
  - marvel cinematic universe
  - ONS
  - NOMIS
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	collapse = TRUE
)
library("tidyverse")
library("ggplot2")

uk_pop <- 65e6
```

## Background

I, like so many nerds, watched [Avengers: Infinity War](https://www.imdb.com/title/tt4154756/?ref_=nv_sr_1), and are eargerly awating part 2. I love how the Marvel Cinematic Universe has built in the interest the X-men movies as a kid, via pulpy action and *all the feels*. 

I'm going to look at Infinity War through the lens of one of Thanos' analysts. What advice might an Operational Analyst for Thanos give?

## Trolley Problem

Thanos, like so many villians who don't see themselves as the villian, hits the viewer with [the trolley problem](https://en.wikipedia.org/wiki/Trolley_problem). In this case: is it morally good to kill half of the population of the universe, in order to save the other half?

Or, in terms of the trolley problem:

"You see a runaway trolley moving towards *the entire population of the universe* lying on the tracks. You are standing next to a lever that controls a switch. If you pull the lever, the trolley will be redirected onto a single side track where *only half the universe* is lying."

Except in this case the "lever" is the infinity gauntlet, and Thanos wasn't so much standing next to the lever as cut a bloody path to it.

Anyway.

## Health Economics

This is a (massively) scaled up problem of health economics. To illustrate, let's take the problem at its lowest level. 

### Triage

A staple of cinema, and the MCU is no exception, is the battlefield triage. For the *best* of this, see [M\*A\*S\*H](https://www.imdb.com/title/tt0068098/?ref_=nv_sr_1). In this situation, the medics have limited resources, they can not treat everyone. They need to work out how to spread their resources (doctors, nurses, medicine, tools, etc.) to save the most people. 

This *is* the trolley problem, sometimes with Hawkeye arguing that he be allowed to work a bit longer on a patient that means 2 more patients will expire in the hallway.

(Or maybe an inverse trolley problem, there is a speeding trolley, and two tracks. You have time to remove 10 people from track A, or 5 people from track B.)

Everyone agrees that it would be best if there were enough resources to save everyone who comes into the MASH unit, but that is not happening.

### Healthcare

The largest problem, as I see it, in Health Economics is the effective use of *limited* resources to maximise health in a population. 

We do not have unlimited doctors, nurses, medicine, tools, etc. so we are dealing with limited resources. (Human staff are the easiest to see this for. Even if we put 100% of our population into medical school, we'd have a limited number of medics.) 

I will talk in the future about the Quality-Adusted Life Year (QALY), but today I will only consider life-years. Except, because it's easier to work with, I'll consider deaths.

# Back to Thanos

Thanos thinks that his policy of grabing all the infinity stones and wiping out half the universe is choosing the track with less people on it.

Except...

What do the analysts say?

## Enough of the ethics, some analysis

I don't know/don't care what the entire population of the MCU is. (Also, I want to work with some other numbers I'm familiar with.) 

Ultimately, Thanos has to choose one of the following two options:
1. Do nothing.
2. Get the infinity gauntlet, and wipe out half the universe.

I'm going to do the sums for both options on the UK, and handwave "if one policy is better in the UK, then it's better in the whole MCU.".

At time of publication, Google thinks the UK population is `r uk_pop`. Which is good enough for my purposes.

Thanos thinks the analysis is easy:

1. `r uk_pop` deaths. 
2. `r uk_pop/2` deaths.

(Any Brits who died while Thanos was getting the gauntlet are a rounding error for these purposes. I'm not falling down the rabithole of who died in Infinity War and where their character is from.)

However, that assumes that the universal catasphroe where everyone dies would have happened right now if not averted. Maybe that's not the case. So let's consider 2 cases:

1. Thanos does nothing, and is right. At some point in the near future everyone dies.
2. Thanos wipes out half the population now, avoiding the death of absolutely everyone in the near future.

Thanos hasn't told us exactly when the death of everyone due to overpopulation is going to happen, so let's assume it happens at some point in the next hundred years. Why 100? Because the ONS have forcasted UK births and deaths for the next 100 years. (With increasing uncertainty...)

